// ===================== EXERCISES.JS =====================
// Baza ćwiczeń GymFlow — 532 ćwiczenia
// Nie edytuj ręcznie — generowane automatycznie

const EXERCISES=[
  // ── KLATKA ──
  {id:'e1', name:'Wyciskanie sztangi na ławce płaskiej (Bench Press)',   muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps','Barki'], category:'wielostawowe',level:'średni',   muscles:{chest:100,triceps:45,frontShoulder:35}},
  {id:'e2', name:'Wyciskanie hantli na ławce skośnej (Incline Dumbbell Bench Press)',     muscle:'Klatka', sub:'Górna klatka',    aux:['Triceps','Barki'], category:'wielostawowe',level:'średni',   muscles:{chest:90,triceps:35,frontShoulder:40}},
  {id:'e2b',name:'Wyciskanie sztangi na ławce skośnej (Incline Bench Press)',    muscle:'Klatka', sub:'Górna klatka',    aux:['Triceps','Barki'], category:'wielostawowe',level:'średni',   muscles:{chest:90,triceps:40,frontShoulder:35}},
  {id:'e2c',name:'Wyciskanie hantli na ławce ujemnej (Decline Dumbbell Bench Press)',     muscle:'Klatka', sub:'Dolna klatka',    aux:['Triceps'],         category:'wielostawowe',level:'średni',   muscles:{chest:95,triceps:40}},
  {id:'e3', name:'Rozpiętki hantlami na ławce płaskiej (Dumbbell Fly)',   muscle:'Klatka', sub:'Środkowa klatka', aux:[],                  category:'izolacja',    level:'łatwy',    muscles:{chest:100,frontShoulder:20}},
  {id:'e3b',name:'Rozpiętki na wyciągu krzyżowym (Cable Crossover Fly)',         muscle:'Klatka', sub:'Środkowa klatka', aux:[],                  category:'izolacja',    level:'łatwy',    muscles:{chest:100}},
  {id:'e3c',name:'Rozpiętki hantlami na ławce skośnej (Incline Dumbbell Fly)',    muscle:'Klatka', sub:'Górna klatka',    aux:[],                  category:'izolacja',    level:'łatwy',    muscles:{chest:95,frontShoulder:25}},
  {id:'e4', name:'Pompki (Push Ups)',                                  muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps','Barki'], category:'wielostawowe',level:'łatwy',    muscles:{chest:80,triceps:50,frontShoulder:30}},
  {id:'e4b',name:'Pompki na poręczach — klatka (Chest Dips)',              muscle:'Klatka', sub:'Dolna klatka',    aux:['Triceps'],         category:'wielostawowe',level:'średni',   muscles:{chest:70,triceps:80}},
  {id:'e5', name:'Wyciskanie na suwnicy Smitha (Smith Machine Bench Press)',            muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'łatwy',    muscles:{chest:95,triceps:40}},
  {id:'e5b',name:'Wyciskanie na maszynie (pec deck)',       muscle:'Klatka', sub:'Środkowa klatka', aux:[],                  category:'izolacja',    level:'łatwy',    muscles:{chest:100}},
  // ── PLECY ──
  {id:'e6', name:'Martwy ciąg klasyczny (Deadlift)',                   muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Pośladki','Biceps'], category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:100,glutes:70,hamstrings:60,traps:50}},
  {id:'e6b',name:'Martwy ciąg rumuński (Romanian Deadlift)',                    muscle:'Plecy',  sub:'Dolne plecy',     aux:['Pośladki','Biceps'],        category:'wielostawowe',level:'średni',     muscles:{lowerBack:80,glutes:80,hamstrings:90}},
  {id:'e6c',name:'Martwy ciąg sumo (Sumo Deadlift)',                        muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Pośladki'],          category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:90,quads:60,hamstrings:60}},
  {id:'e7', name:'Podciąganie na drążku (nachwytem)',        muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],      category:'wielostawowe',level:'średni',   muscles:{lats:100,biceps:60,rearShoulder:30}},
  {id:'e7b',name:'Podciąganie na drążku (podchwytem)',      muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],      category:'wielostawowe',level:'średni',   muscles:{lats:90,biceps:80}},
  {id:'e8', name:'Wiosłowanie sztangą w skłonie (Bent Over Row)',           muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],         category:'wielostawowe',level:'średni',   muscles:{lats:80,traps:60,biceps:50}},
  {id:'e8b',name:'Wiosłowanie T-bar (T-Bar Row)',                       muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],         category:'wielostawowe',level:'średni',   muscles:{lats:75,traps:65,biceps:45}},
  {id:'e9', name:'Ściąganie linek na wyciągu górnym (Lat Pulldown)',       muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],      category:'izolacja',    level:'łatwy',    muscles:{lats:100,biceps:40}},
  {id:'e9b',name:'Ściąganie linki do klatki (Seated Cable Row)',muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],         category:'izolacja',    level:'łatwy',    muscles:{lats:70,traps:60,biceps:35}},
  {id:'e10',name:'Wiosłowanie hantlem jednostronnie (Dumbbell One Arm Row)',       muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],      category:'wielostawowe',level:'łatwy',    muscles:{lats:85,traps:40,biceps:45}},
  {id:'e10b',name:'Facepull (Face Pull)',                      muscle:'Plecy',  sub:'Tylny bark',      aux:['Barki'],          category:'izolacja',    level:'łatwy',    muscles:{rearShoulder:100,traps:50}},
  {id:'e10c',name:'Hiper-ekstensje (Hyperextensions)',                        muscle:'Plecy',  sub:'Dolne plecy',     aux:['Pośladki'],       category:'izolacja',    level:'łatwy',    muscles:{lowerBack:100,glutes:50}},
  {id:'e10d',name:'Szrugi ze sztangą (Barbell Shrug)',                      muscle:'Plecy',  sub:'Czworoboczny',    aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{traps:100}},
  // ── BARKI ──
  {id:'e17',name:'Wyciskanie żołnierskie sztangą (OHP)',    muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps'],        category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:60,triceps:50}},
  {id:'e17b',name:'Wyciskanie hantlami nad głowę (Dumbbell Overhead Press)',         muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps'],        category:'wielostawowe',level:'średni',   muscles:{frontShoulder:90,midShoulder:60,triceps:45}},
  {id:'e17c',name:'Wyciskanie Arnolda (Arnold Press)',                    muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps'],        category:'wielostawowe',level:'średni',   muscles:{frontShoulder:85,midShoulder:80,triceps:40}},
  {id:'e18',name:'Boczne unoszenie hantli (Dumbbell Lateral Raise)',                muscle:'Barki',  sub:'Boczny bark',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{midShoulder:100,frontShoulder:20}},
  {id:'e18b',name:'Boczne unoszenie na wyciągu (Cable Lateral Raise)',          muscle:'Barki',  sub:'Boczny bark',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{midShoulder:100}},
  {id:'e19',name:'Wznosy hantli w opadzie (Rear Delt Fly)',    muscle:'Barki',  sub:'Tylny bark',      aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{rearShoulder:100,traps:30}},
  {id:'e19b',name:'Wznosy przedramion (Dumbbell Front Raise)',     muscle:'Barki',  sub:'Przedni bark',    aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{frontShoulder:100}},
  // ── BICEPS ──
  {id:'e20',name:'Uginanie ramion z hantlami (Dumbbell Curl)',            muscle:'Biceps', sub:'Biceps',          aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{biceps:100}},
  {id:'e21',name:'Uginanie z EZ-barem (EZ Bar Curl)',                   muscle:'Biceps', sub:'Biceps',          aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{biceps:100}},
  {id:'e21b',name:'Uginanie ramion ze sztangą prostą (Barbell Curl)',    muscle:'Biceps', sub:'Biceps',          aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{biceps:100,forearms:30}},
  {id:'e21c',name:'Uginanie na modlitewniku (Preacher Curl)',             muscle:'Biceps', sub:'Głowa długa biceps', aux:[],              category:'izolacja',    level:'łatwy',    muscles:{biceps:100}},
  {id:'e21d',name:'Uginanie młotkowe (Hammer Curl)',      muscle:'Biceps', sub:'Brachialis',      aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{biceps:80,forearms:60}},
  {id:'e21e',name:'Uginanie kablowe (Cable Bicep Curl)',            muscle:'Biceps', sub:'Biceps',          aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{biceps:100}},
  // ── TRICEPS ──
  {id:'e22',name:'Prostowanie ramion na wyciągu (Tricep Pushdown)',         muscle:'Triceps',sub:'Triceps',         aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{triceps:100}},
  {id:'e23',name:'Wyciskanie wąskim chwytem (Close Grip Bench Press)',             muscle:'Triceps',sub:'Głowa długa triceps', aux:['Klatka'],     category:'wielostawowe',level:'średni',   muscles:{triceps:100,chest:40}},
  {id:'e23b',name:'French press (EZ Bar Lying Tricep Extension)',               muscle:'Triceps',sub:'Głowa długa triceps', aux:[],             category:'izolacja',    level:'średni',   muscles:{triceps:100}},
  {id:'e23c',name:'Pompki na poręczach — triceps (Tricep Dips)',   muscle:'Triceps',sub:'Triceps',         aux:[],                 category:'wielostawowe',level:'średni',   muscles:{triceps:100,chest:30}},
  {id:'e23d',name:'Kopnięcia tyłem z hantlą (Tricep Kickback)',            muscle:'Triceps',sub:'Głowa boczna',    aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{triceps:100}},
  {id:'e23e',name:'Skull crusher z EZ-barem (EZ Bar Skull Crusher)',            muscle:'Triceps',sub:'Głowa długa triceps', aux:[],             category:'izolacja',    level:'średni',   muscles:{triceps:100}},
  // ── NOGI ──
  {id:'e11',name:'Przysiad ze sztangą (Back Squat)',      muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki','Łydki'], category:'wielostawowe',level:'zaawansowany',muscles:{quads:100,glutes:60,hamstrings:40,calves:20}},
  {id:'e11b',name:'Przysiad przedni (Front Squat)',       muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'zaawansowany',muscles:{quads:100,glutes:50}},
  {id:'e11c',name:'Goblet squat z kettlebell (Kettlebell Goblet Squat)',            muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'łatwy',    muscles:{quads:90,glutes:60}},
  {id:'e12',name:'Wykroki z hantlami (Dumbbell Lunge)',                    muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'średni',   muscles:{quads:85,glutes:70,hamstrings:30}},
  {id:'e12b',name:'Krok bułgarski z hantlami (Bulgarian Split Squat)',           muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'średni',   muscles:{quads:90,glutes:75}},
  {id:'e12c',name:'Wykroki na bieżni (Walking Lunge)',   muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'średni',   muscles:{quads:85,glutes:70}},
  {id:'e13',name:'Prostowanie nóg na maszynie (Leg Extension)',           muscle:'Nogi',   sub:'Czworogłowe',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{quads:100}},
  {id:'e14',name:'Uginanie nóg leżąc (Lying Leg Curl)',         muscle:'Nogi',   sub:'Dwugłowe ud',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{hamstrings:100}},
  {id:'e14b',name:'Uginanie nóg siedząc (Seated Leg Curl)',      muscle:'Nogi',   sub:'Dwugłowe ud',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{hamstrings:100}},
  {id:'e14c',name:'Good morning (Good Morning)',                         muscle:'Nogi',   sub:'Dwugłowe ud',     aux:['Plecy'],          category:'wielostawowe',level:'średni',   muscles:{hamstrings:80,lowerBack:70,glutes:50}},
  {id:'e15',name:'Wznosy łydek stojąc (Standing Calf Raise)',                  muscle:'Łydki',  sub:'Łydki',           aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{calves:100}},
  {id:'e15b',name:'Wznosy łydek siedząc (Seated Calf Raise)',      muscle:'Łydki',  sub:'Soleus',          aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{calves:100}},
  {id:'e15c',name:'Skakanka (Jump Rope)',              muscle:'Łydki',  sub:'Łydki',           aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{calves:80}},
  {id:'e11d',name:'Leg press (Leg Press)',                muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'łatwy',    muscles:{quads:100,glutes:50,hamstrings:30}},
  {id:'e11e',name:'Hack squat (Hack Squat Machine)',                 muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],       category:'wielostawowe',level:'średni',   muscles:{quads:100,glutes:40}},
  // ── POŚLADKI ──
  {id:'e16',name:'Hip thrust ze sztangą (Barbell Hip Thrust)',                 muscle:'Pośladki',sub:'Pośladki',       aux:['Dwugłowe ud'],    category:'wielostawowe',level:'średni',   muscles:{glutes:100,hamstrings:50}},
  {id:'e16b',name:'Hip thrust z hantlą (Dumbbell Hip Thrust)',                  muscle:'Pośladki',sub:'Pośladki',       aux:[],                 category:'wielostawowe',level:'łatwy',    muscles:{glutes:100,hamstrings:40}},
  {id:'e16c',name:'Abdukcja bioder (Hip Abduction Machine)',     muscle:'Pośladki',sub:'Pośladki małe',   aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{glutes:80}},
  {id:'e16d',name:'Mostek biodrowy (Glute Bridge)',       muscle:'Pośladki',sub:'Pośladki',       aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{glutes:100,hamstrings:30}},
  {id:'e16e',name:'Donkey kicks (Donkey Kicks)',                         muscle:'Pośladki',sub:'Pośladki',       aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{glutes:100}},
  // ── BRZUCH ──
  {id:'e24',name:'Plank (Plank)',                                  muscle:'Brzuch', sub:'Mięśnie proste', aux:[],                 category:'core',        level:'łatwy',    muscles:{abs:100,lowerBack:40}},
  {id:'e25',name:'Crunch klasyczny (Crunch)',                       muscle:'Brzuch', sub:'Mięśnie proste', aux:[],                 category:'core',        level:'łatwy',    muscles:{abs:100}},
  {id:'e25b',name:'Crunch na maszynie (Machine Crunch)',                    muscle:'Brzuch', sub:'Mięśnie proste', aux:[],                 category:'core',        level:'łatwy',    muscles:{abs:100}},
  {id:'e26',name:'Leg raise w zwisie (Hanging Leg Raise)',                    muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                 category:'core',        level:'średni',   muscles:{abs:90}},
  {id:'e26b',name:'Unoszenie nóg leżąc (Lying Leg Raise)',                  muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                 category:'core',        level:'łatwy',    muscles:{abs:85}},
  {id:'e26c',name:'Russian twist (Russian Twist)',                         muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                 category:'core',        level:'średni',   muscles:{abs:80}},
  {id:'e26d',name:'Bicycle crunch (Bicycle Crunch)',                        muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                 category:'core',        level:'średni',   muscles:{abs:85}},
  {id:'e26e',name:'Ab rollout (Ab Wheel Rollout)',                    muscle:'Brzuch', sub:'Mięśnie proste', aux:['Plecy'],          category:'core',        level:'zaawansowany',muscles:{abs:100,lowerBack:50}},
  {id:'e26f',name:'Plank boczny (Side Plank)',                          muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                 category:'core',        level:'łatwy',    muscles:{abs:80}},
  {id:'e26g',name:'Cable crunch (Cable Crunch)',                 muscle:'Brzuch', sub:'Mięśnie proste', aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{abs:100}},
  // ── PRZEDRAMIONA ──
  {id:'e27',name:'Uginanie nadgarstków z hantlami (Wrist Curl)',        muscle:'Łydki',  sub:'Przedramiona',   aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{forearms:100}},
  {id:'e27b',name:'Reverse curl (podchwytem)',             muscle:'Biceps', sub:'Brachialis',     aux:[],                 category:'izolacja',    level:'łatwy',    muscles:{forearms:80,biceps:40}},
  {id:'e27c',name:'Farmer carry (Farmers Walk)',                          muscle:'Plecy',  sub:'Czworoboczny',   aux:['Brzuch'],         category:'wielostawowe',level:'średni',   muscles:{forearms:70,traps:80,abs:50}},

  // ── KLATKA — dodatkowe ──
  {id:'f1', name:'Wyciskanie szerokim chwytem (Wide Grip Bench Press)',            muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps','Barki'], category:'wielostawowe',level:'średni',      muscles:{chest:100,triceps:35,frontShoulder:30}},
  {id:'f2', name:'Wyciskanie na podłodze z hantlami (Dumbbell Floor Press)',       muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'łatwy',       muscles:{chest:90,triceps:50}},
  {id:'f3', name:'Wyciskanie w maszynie (Chest Press)',                            muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'łatwy',       muscles:{chest:100,triceps:35}},
  {id:'f4', name:'Wyciskanie skośne w maszynie (Incline Machine Bench Press)',     muscle:'Klatka', sub:'Górna klatka',    aux:['Triceps'],         category:'wielostawowe',level:'łatwy',       muscles:{chest:90,triceps:35,frontShoulder:40}},
  {id:'f5', name:'Rozpiętki skośne w dół (Decline Dumbbell Fly)',                 muscle:'Klatka', sub:'Dolna klatka',    aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{chest:100}},
  {id:'f6', name:'Wyciskanie skośnie w dół z hantlami (Decline Dumbbell Bench Press)', muscle:'Klatka', sub:'Dolna klatka', aux:['Triceps'],       category:'wielostawowe',level:'średni',      muscles:{chest:95,triceps:40}},
  {id:'f7', name:'Wyciskanie skośnie w dół ze sztangą (Decline Bench Press)',     muscle:'Klatka', sub:'Dolna klatka',    aux:['Triceps'],         category:'wielostawowe',level:'średni',      muscles:{chest:95,triceps:40}},
  {id:'f8', name:'Rozciąganie na wyciągu krzyżowym (Cable Fly)',                   muscle:'Klatka', sub:'Środkowa klatka', aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{chest:100,frontShoulder:20}},
  {id:'f9', name:'Pompki na kolanach (Knee Push Ups)',                             muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps','Barki'], category:'wielostawowe',level:'łatwy',       muscles:{chest:75,triceps:45,frontShoulder:25}},
  {id:'f10',name:'Pompki szerokie (Wide Grip Push Ups)',                           muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps','Barki'], category:'wielostawowe',level:'łatwy',       muscles:{chest:85,triceps:40,frontShoulder:30}},
  {id:'f11',name:'Pompki diamentowe (Diamond Push Ups)',                           muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'średni',      muscles:{chest:60,triceps:90}},
  {id:'f12',name:'Wyciskanie wąskim chwytem skośnie (Close Grip Incline Bench Press)', muscle:'Klatka', sub:'Górna klatka', aux:['Triceps'],       category:'wielostawowe',level:'średni',      muscles:{chest:80,triceps:80,frontShoulder:30}},
  {id:'f13',name:'Spoto Press',                                                    muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'zaawansowany', muscles:{chest:100,triceps:50}},
  {id:'f14',name:'Wyciskanie Larsen (Larsen Press)',                               muscle:'Klatka', sub:'Środkowa klatka', aux:['Triceps'],         category:'wielostawowe',level:'zaawansowany', muscles:{chest:100,triceps:55}},
  {id:'f15',name:'Pullover ze sztangą (Barbell Pullover)',                         muscle:'Klatka', sub:'Środkowa klatka', aux:['Plecy'],           category:'izolacja',    level:'średni',      muscles:{chest:80,lats:60}},
  {id:'f16',name:'Pullover z hantlem (Dumbbell Pullover)',                         muscle:'Klatka', sub:'Środkowa klatka', aux:['Plecy'],           category:'izolacja',    level:'łatwy',       muscles:{chest:80,lats:60}},

  // ── PLECY — dodatkowe ──
  {id:'g1', name:'Wiosłowanie szerokim chwytem siedząc (Wide Grip Seated Cable Row)', muscle:'Plecy', sub:'Najszerszy grzbiet', aux:['Biceps'],     category:'wielostawowe',level:'łatwy',       muscles:{lats:100,biceps:40,traps:40}},
  {id:'g2', name:'Wiosłowanie w maszynie siedząc (Seated Machine Row)',            muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],          category:'wielostawowe',level:'łatwy',       muscles:{lats:80,traps:60,biceps:50}},
  {id:'g3', name:'Wiosłowanie odwróconym chwytem w skłonie (Reverse Grip Bent Over Row)', muscle:'Plecy', sub:'Najszerszy grzbiet', aux:['Biceps'], category:'wielostawowe',level:'średni',      muscles:{lats:90,biceps:60}},
  {id:'g4', name:'Wiosłowanie Pendlay (Pendlay Row)',                              muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],          category:'wielostawowe',level:'zaawansowany', muscles:{lats:80,traps:70,biceps:50}},
  {id:'g5', name:'Wiosłowanie Meadows (Meadows Row)',                              muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],        category:'wielostawowe',level:'zaawansowany', muscles:{lats:100,biceps:40}},
  {id:'g6', name:'Wiosłowanie w opadzie z hantlami (Bent Over Dumbbell Row)',     muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],          category:'wielostawowe',level:'łatwy',       muscles:{lats:80,traps:50,biceps:45}},
  {id:'g7', name:'Ściąganie wąskim chwytem (Close Grip Lat Pulldown)',            muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],        category:'izolacja',    level:'łatwy',       muscles:{lats:100,biceps:50}},
  {id:'g8', name:'Ściąganie jedną ręką (Single Arm Lat Pulldown)',                muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Biceps'],        category:'izolacja',    level:'łatwy',       muscles:{lats:100,biceps:40}},
  {id:'g9', name:'Wiosłowanie TRX (TRX Row)',                                     muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],          category:'wielostawowe',level:'łatwy',       muscles:{lats:80,traps:50,biceps:40}},
  {id:'g10',name:'Wiosłowanie odwrócone (Inverted Row)',                           muscle:'Plecy',  sub:'Środkowe plecy',  aux:['Biceps'],          category:'wielostawowe',level:'łatwy',       muscles:{lats:80,traps:50,biceps:40}},
  {id:'g11',name:'Martwy ciąg z hantlami (Dumbbell Deadlift)',                    muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Pośladki'], category:'wielostawowe',level:'średni',      muscles:{lowerBack:90,glutes:65,hamstrings:55}},
  {id:'g12',name:'Martwy ciąg hex bar (Hex Bar Deadlift)',                        muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Pośladki'], category:'wielostawowe',level:'średni',      muscles:{lowerBack:90,quads:60,glutes:65,hamstrings:55}},
  {id:'g13',name:'Martwy ciąg z deficytu (Deficit Deadlift)',                     muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Pośladki'], category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:100,glutes:70,hamstrings:65}},
  {id:'g14',name:'Rack pull',                                                      muscle:'Plecy',  sub:'Dolne plecy',     aux:['Pośladki'],        category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:100,traps:60,glutes:50}},
  {id:'g15',name:'Martwy ciąg stiff leg (Stiff Leg Deadlift)',                    muscle:'Plecy',  sub:'Dolne plecy',     aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{lowerBack:80,hamstrings:100,glutes:60}},
  {id:'g16',name:'Prostowanie ramion w dół (Straight Arm Pulldown)',              muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{lats:100}},
  {id:'g17',name:'Unoszenie tułowia (Back Extension)',                             muscle:'Plecy',  sub:'Dolne plecy',     aux:['Pośladki'],        category:'izolacja',    level:'łatwy',       muscles:{lowerBack:100,glutes:40}},
  {id:'g18',name:'Ściąganie Y na wyciągu (Cable Y Raise)',                        muscle:'Plecy',  sub:'Czworoboczny',    aux:['Barki'],           category:'izolacja',    level:'łatwy',       muscles:{traps:80,rearShoulder:60}},
  {id:'g19',name:'Renegade row',                                                   muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Brzuch','Biceps'], category:'wielostawowe',level:'zaawansowany', muscles:{lats:80,abs:70,biceps:40}},
  {id:'g20',name:'Szrugi ze sztangą za plecami (Behind the Back Barbell Shrug)',  muscle:'Plecy',  sub:'Czworoboczny',    aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{traps:100}},

  // ── BARKI — dodatkowe ──
  {id:'h1', name:'Wyciskanie za głowę (Behind the Neck Press)',                   muscle:'Barki',  sub:'Boczny bark',     aux:['Triceps'],         category:'wielostawowe',level:'zaawansowany', muscles:{midShoulder:100,frontShoulder:50,triceps:45}},
  {id:'h2', name:'Push press ze sztangą (Push Press)',                             muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps','Nogi'],  category:'wielostawowe',level:'zaawansowany', muscles:{frontShoulder:100,midShoulder:60,triceps:50,quads:30}},
  {id:'h3', name:'Unoszenie ramion w bok na maszynie (Machine Lateral Raise)',    muscle:'Barki',  sub:'Boczny bark',     aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{midShoulder:100}},
  {id:'h4', name:'Wyciskanie w maszynie (Machine Shoulder Press)',                muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps'],         category:'wielostawowe',level:'łatwy',       muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'h5', name:'Unoszenie ramion w bok na wyciągu (Cable Lateral Raise)',       muscle:'Barki',  sub:'Boczny bark',     aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{midShoulder:100}},
  {id:'h6', name:'Odwrotne rozpiętki na wyciągu (Cable Reverse Fly)',             muscle:'Barki',  sub:'Tylny bark',      aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{rearShoulder:100,traps:30}},
  {id:'h7', name:'Wiosłowanie do brody (Upright Row)',                            muscle:'Barki',  sub:'Boczny bark',     aux:['Biceps','Plecy'],  category:'wielostawowe',level:'średni',      muscles:{midShoulder:80,frontShoulder:60,biceps:40,traps:70}},
  {id:'h8', name:'Wiosłowanie do brody na wyciągu (Cable Upright Row)',           muscle:'Barki',  sub:'Boczny bark',     aux:['Biceps'],          category:'wielostawowe',level:'łatwy',       muscles:{midShoulder:80,frontShoulder:60,biceps:40,traps:65}},
  {id:'h9', name:'Wznosy ramion przodem na wyciągu (Cable Front Raise)',          muscle:'Barki',  sub:'Przedni bark',    aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{frontShoulder:100}},
  {id:'h10',name:'Wyciskanie hantlami siedząc (Seated Dumbbell Shoulder Press)',  muscle:'Barki',  sub:'Przedni bark',    aux:['Triceps'],         category:'wielostawowe',level:'łatwy',       muscles:{frontShoulder:90,midShoulder:60,triceps:40}},
  {id:'h11',name:'Facepull na wyciągu (Face Pull)',                               muscle:'Barki',  sub:'Tylny bark',      aux:['Plecy'],           category:'izolacja',    level:'łatwy',       muscles:{rearShoulder:100,traps:50}},
  {id:'h12',name:'Wyciskanie landmine (One Arm Landmine Press)',                  muscle:'Barki',  sub:'Przedni bark',    aux:['Klatka','Triceps'], category:'wielostawowe',level:'średni',     muscles:{frontShoulder:90,chest:50,triceps:40}},
  {id:'h13',name:'Viking press',                                                   muscle:'Barki',  sub:'Boczny bark',     aux:['Triceps'],         category:'wielostawowe',level:'zaawansowany', muscles:{frontShoulder:100,midShoulder:70,triceps:50}},

  // ── BICEPS — dodatkowe ──
  {id:'i1', name:'Uginanie na wyciągu (Cable Bicep Curl)',                        muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i2', name:'Uginanie jedną ręką na wyciągu (One Arm Cable Bicep Curl)',     muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i3', name:'Uginanie skośne na ławce (Incline Dumbbell Curl)',              muscle:'Biceps', sub:'Głowa długa biceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i4', name:'Uginanie pajęcze (Spider Curl)',                                muscle:'Biceps', sub:'Głowa długa biceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i5', name:'Uginanie skośne młotkowe (Incline Hammer Curl)',                muscle:'Biceps', sub:'Brachialis',      aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:80,forearms:60}},
  {id:'i6', name:'Uginanie siedząc (Seated Dumbbell Curl)',                       muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i7', name:'Uginanie Bayesian (Bayesian Curl)',                             muscle:'Biceps', sub:'Głowa długa biceps', aux:[],               category:'izolacja',    level:'średni',      muscles:{biceps:100}},
  {id:'i8', name:'Uginanie TRX (TRX Bicep Curl)',                                muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i9', name:'Uginanie na maszynie (Machine Bicep Curl)',                     muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i10',name:'Uginanie na modlitewniku EZ (EZ Bar Preacher Curl)',            muscle:'Biceps', sub:'Głowa krótka biceps', aux:[],              category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i11',name:'Uginanie pająk EZ (EZ Bar Spider Curl)',                        muscle:'Biceps', sub:'Głowa długa biceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i12',name:'Uginanie krzyżowe (Cross Body Hammer Curl)',                    muscle:'Biceps', sub:'Brachialis',      aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{biceps:80,forearms:60}},
  {id:'i13',name:'Uginanie ścisłe (Strict Curl)',                                 muscle:'Biceps', sub:'Biceps',          aux:[],                  category:'izolacja',    level:'zaawansowany', muscles:{biceps:100}},
  {id:'i14',name:'Uginanie Zottman (Zottman Curl)',                               muscle:'Biceps', sub:'Brachialis',      aux:[],                  category:'izolacja',    level:'średni',      muscles:{biceps:90,forearms:80}},
  {id:'i15',name:'Uginanie waiter (Waiter Curl)',                                 muscle:'Biceps', sub:'Głowa długa biceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},
  {id:'i16',name:'Uginanie modlitewnik maszyna (Machine Preacher Curl)',          muscle:'Biceps', sub:'Głowa krótka biceps', aux:[],              category:'izolacja',    level:'łatwy',       muscles:{biceps:100}},

  // ── TRICEPS — dodatkowe ──
  {id:'j1', name:'Prostowanie odwróconym chwytem (Reverse Grip Tricep Pushdown)', muscle:'Triceps',sub:'Głowa boczna',    aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j2', name:'Prostowanie przez ciało (Cross Body Cable Tricep Extension)',   muscle:'Triceps',sub:'Głowa długa triceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j3', name:'Prostowanie leżąc z hantlem (Dumbbell Tricep Extension)',       muscle:'Triceps',sub:'Głowa długa triceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j4', name:'Prostowanie siedząc (Seated Dumbbell Tricep Extension)',        muscle:'Triceps',sub:'Głowa długa triceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j5', name:'JM Press',                                                       muscle:'Triceps',sub:'Triceps',         aux:['Klatka'],           category:'wielostawowe',level:'zaawansowany', muscles:{triceps:100,chest:40}},
  {id:'j6', name:'Tate Press',                                                     muscle:'Triceps',sub:'Głowa boczna',    aux:[],                  category:'izolacja',    level:'średni',      muscles:{triceps:100}},
  {id:'j7', name:'Dociśnięcia na ławce (Bench Dips)',                             muscle:'Triceps',sub:'Triceps',         aux:[],                   category:'wielostawowe',level:'łatwy',       muscles:{triceps:100,chest:20}},
  {id:'j8', name:'Prostowanie TRX (TRX Triceps Extension)',                       muscle:'Triceps',sub:'Głowa długa triceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j9', name:'Prostowanie na wyciągu górnym (Cable Overhead Tricep Extension)', muscle:'Triceps',sub:'Głowa długa triceps', aux:[],             category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},
  {id:'j10',name:'Prostowanie leżąc ze sztangą (Lying Tricep Extension)',         muscle:'Triceps',sub:'Głowa długa triceps', aux:[],               category:'izolacja',    level:'łatwy',       muscles:{triceps:100}},

  // ── NOGI — dodatkowe ──
  {id:'k1', name:'Przysiad bułgarski ze sztangą (Barbell Bulgarian Split Squat)', muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'zaawansowany', muscles:{quads:90,glutes:75}},
  {id:'k2', name:'Przysiad bułgarski w Smithie (Smith Machine Bulgarian Split Squat)', muscle:'Nogi', sub:'Czworogłowe', aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{quads:90,glutes:75}},
  {id:'k3', name:'Przysiad sumo (Sumo Squat)',                                    muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:80,glutes:80,hamstrings:40}},
  {id:'k4', name:'Przysiad z pauzą (Pause Squat)',                                muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'zaawansowany', muscles:{quads:100,glutes:60}},
  {id:'k5', name:'Przysiad na skrzyni (Box Squat)',                               muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{quads:95,glutes:70}},
  {id:'k6', name:'Przysiad na jednej nodze (Pistol Squat)',                       muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'zaawansowany', muscles:{quads:100,glutes:60}},
  {id:'k7', name:'Przysiad sissy (Sissy Squat)',                                  muscle:'Nogi',   sub:'Czworogłowe',     aux:[],                  category:'izolacja',    level:'zaawansowany', muscles:{quads:100}},
  {id:'k8', name:'Wchodzenie na skrzynię (Step Ups)',                             muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:85,glutes:70}},
  {id:'k9', name:'Wyskok na skrzynię (Box Jump)',                                 muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{quads:90,glutes:70,calves:40}},
  {id:'k10',name:'Norski curl (Reverse Nordic Curl)',                              muscle:'Nogi',   sub:'Czworogłowe',     aux:[],                  category:'izolacja',    level:'zaawansowany', muscles:{quads:100}},
  {id:'k11',name:'Uginanie nóg stojąc (Standing Leg Curl)',                       muscle:'Nogi',   sub:'Dwugłowe ud',     aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{hamstrings:100}},
  {id:'k12',name:'Uginanie nóg jednonóż (Single Leg Lying Leg Curl)',             muscle:'Nogi',   sub:'Dwugłowe ud',     aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{hamstrings:100}},
  {id:'k13',name:'Glute ham raise',                                               muscle:'Nogi',   sub:'Dwugłowe ud',     aux:['Pośladki'],        category:'wielostawowe',level:'zaawansowany', muscles:{hamstrings:100,glutes:60}},
  {id:'k14',name:'Przysiad plie (Plie Squat)',                                    muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:80,glutes:80}},
  {id:'k15',name:'Wykroki chodzące (Walking Lunge)',                              muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:85,glutes:70}},
  {id:'k16',name:'Wykroki ze sztangą (Barbell Lunge)',                            muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{quads:90,glutes:70}},
  {id:'k17',name:'Przysiad z hantlami (Dumbbell Squat)',                          muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:95,glutes:60}},
  {id:'k18',name:'Wznosy łydek jednonóż siedząc (Single Leg Seated Calf Raise)', muscle:'Łydki',  sub:'Soleus',          aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{calves:100}},
  {id:'k19',name:'Wznosy łydek na hack squat (Hack Squat Calf Raise)',            muscle:'Łydki',  sub:'Łydki',           aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{calves:100}},
  {id:'k20',name:'Prasa na łydki (Machine Calf Press)',                           muscle:'Łydki',  sub:'Łydki',           aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{calves:100}},
  {id:'k21',name:'Wznosy łydek ze sztangą (Barbell Calf Raise)',                  muscle:'Łydki',  sub:'Łydki',           aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{calves:100}},
  {id:'k22',name:'Belt squat',                                                     muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'średni',      muscles:{quads:100,glutes:60}},
  {id:'k23',name:'Reverse hyperextension',                                        muscle:'Nogi',   sub:'Dwugłowe ud',     aux:['Pośladki','Plecy'], category:'izolacja',   level:'średni',      muscles:{hamstrings:70,glutes:80,lowerBack:50}},
  {id:'k24',name:'Odwodzenie bioder w leżeniu (Clamshells)',                      muscle:'Pośladki',sub:'Pośladki małe',  aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{glutes:80}},
  {id:'k25',name:'Odwodzenie bioder na wyciągu (Cable Standing Hip Abduction)',   muscle:'Pośladki',sub:'Pośladki małe',  aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{glutes:80}},
  {id:'k26',name:'Przywodzenie bioder (Hip Adduction)',                           muscle:'Nogi',   sub:'Przywodziciele',  aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{hamstrings:40}},
  {id:'k27',name:'Prasa nóg jednonóż (Single Leg Press)',                         muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'wielostawowe',level:'łatwy',       muscles:{quads:100,glutes:50}},

  // ── POŚLADKI — dodatkowe ──
  {id:'l1', name:'Mostek jednonóż (Single Leg Glute Bridge)',                     muscle:'Pośladki',sub:'Pośladki',       aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{glutes:100,hamstrings:30}},
  {id:'l2', name:'Mostek biodrowy ze sztangą (Barbell Glute Bridge)',             muscle:'Pośladki',sub:'Pośladki',       aux:[],                  category:'wielostawowe',level:'łatwy',       muscles:{glutes:100,hamstrings:40}},
  {id:'l3', name:'Kopnięcia tyłem na wyciągu (Cable Glute Kickback)',             muscle:'Pośladki',sub:'Pośladki',       aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{glutes:100}},
  {id:'l4', name:'Kopnięcia tyłem na maszynie (Machine Glute Kickback)',          muscle:'Pośladki',sub:'Pośladki',       aux:[],                  category:'izolacja',    level:'łatwy',       muscles:{glutes:100}},
  {id:'l5', name:'Przeciągnięcie na wyciągu (Cable Pull Through)',                muscle:'Pośladki',sub:'Pośladki',       aux:['Plecy'],           category:'wielostawowe',level:'łatwy',       muscles:{glutes:100,hamstrings:60,lowerBack:40}},

  // ── BRZUCH — dodatkowe ──
  {id:'m1', name:'Rotacja tułowia na maszynie (Torso Rotation Machine)',          muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:80}},
  {id:'m2', name:'Spięcia stojąc na wyciągu (Standing Cable Crunch)',             muscle:'Brzuch', sub:'Mięśnie proste',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:100}},
  {id:'m3', name:'Unoszenie kolan w zwisie (Hanging Knee Raise)',                 muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:85}},
  {id:'m4', name:'Nożyce poziome (Flutter Kicks)',                                 muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:85}},
  {id:'m5', name:'Wspinaczka górska (Mountain Climbers)',                          muscle:'Brzuch', sub:'Mięśnie proste',  aux:['Barki'],           category:'core',        level:'łatwy',       muscles:{abs:80,frontShoulder:30}},
  {id:'m6', name:'Wiatraki w zwisie (Hanging Windshield Wipers)',                 muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                  category:'core',        level:'zaawansowany', muscles:{abs:90}},
  {id:'m7', name:'Wspinanie nóg do drążka (Toes to Bar)',                         muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                  category:'core',        level:'zaawansowany', muscles:{abs:100}},
  {id:'m8', name:'Dragon flag',                                                    muscle:'Brzuch', sub:'Mięśnie proste',  aux:[],                  category:'core',        level:'zaawansowany', muscles:{abs:100}},
  {id:'m9', name:'Spięcia boczne (Side Crunch)',                                  muscle:'Brzuch', sub:'Skośne brzucha',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:80}},
  {id:'m10',name:'Spięcia podwójne (Double Crunches)',                             muscle:'Brzuch', sub:'Mięśnie proste',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:100}},
  {id:'m11',name:'Plank wysoki (High Plank)',                                      muscle:'Brzuch', sub:'Mięśnie proste',  aux:['Barki'],           category:'core',        level:'łatwy',       muscles:{abs:90,frontShoulder:30}},
  {id:'m12',name:'Plank odwrócony (Reverse Plank)',                               muscle:'Brzuch', sub:'Mięśnie proste',  aux:['Plecy'],           category:'core',        level:'łatwy',       muscles:{abs:70,glutes:60,lowerBack:50}},
  {id:'m13',name:'Nożyce pionowe (Lying Leg Raise)',                              muscle:'Brzuch', sub:'Dolny brzuch',    aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:90}},
  {id:'m14',name:'Spięcia na ławce skośnej (Decline Crunch)',                     muscle:'Brzuch', sub:'Mięśnie proste',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:100}},
  {id:'m15',name:'Sit-up na ławce skośnej (Decline Sit-up)',                      muscle:'Brzuch', sub:'Mięśnie proste',  aux:[],                  category:'core',        level:'łatwy',       muscles:{abs:100}},

  // ── OLIMPIJSKIE / WIELOSTAWOWE ──
  {id:'n1', name:'Rwanie (Snatch)',                                                muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Barki'],    category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:80,glutes:80,quads:70,frontShoulder:60,traps:70}},
  {id:'n2', name:'Dwubój olimpijski (Clean and Jerk)',                             muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi','Barki'],    category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:80,glutes:80,quads:70,frontShoulder:80,triceps:50}},
  {id:'n3', name:'Zarzut sztangi (Power Clean)',                                   muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi'],            category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:80,glutes:70,quads:60,traps:60}},
  {id:'n4', name:'Zarzut z podwieszenia (Hang Power Clean)',                       muscle:'Plecy',  sub:'Dolne plecy',     aux:['Nogi'],            category:'wielostawowe',level:'zaawansowany', muscles:{lowerBack:70,glutes:65,quads:55,traps:55}},
  {id:'n5', name:'Przysiad z wypchnięciem (Thruster)',                             muscle:'Nogi',   sub:'Czworogłowe',     aux:['Barki'],           category:'wielostawowe',level:'zaawansowany', muscles:{quads:90,glutes:60,frontShoulder:80,triceps:40}},
  {id:'n6', name:'Swing kettlebell (Kettlebell Swing)',                            muscle:'Pośladki',sub:'Pośladki',       aux:['Plecy','Nogi'],    category:'wielostawowe',level:'średni',      muscles:{glutes:100,hamstrings:70,lowerBack:60}},
  {id:'n7', name:'Burpees',                                                         muscle:'Klatka', sub:'Środkowa klatka', aux:['Nogi','Brzuch'],   category:'wielostawowe',level:'średni',      muscles:{chest:60,quads:60,abs:50,frontShoulder:40}},
  {id:'n8', name:'Wyciskanie hantlami z przysiadem (Dumbbell Thruster)',           muscle:'Nogi',   sub:'Czworogłowe',     aux:['Barki'],           category:'wielostawowe',level:'zaawansowany', muscles:{quads:85,glutes:60,frontShoulder:80,triceps:40}},
  {id:'n9', name:'Get-up kettlebell (Kettlebell Turkish Get Up)',                  muscle:'Barki',  sub:'Przedni bark',    aux:['Brzuch','Nogi'],   category:'wielostawowe',level:'zaawansowany', muscles:{frontShoulder:70,abs:70,quads:50}},

  // ── CARDIO ──
  {id:'o1', name:'Bieganie (Running)',                                             muscle:'Nogi',   sub:'Czworogłowe',     aux:['Łydki'],           category:'cardio',      level:'łatwy',       muscles:{quads:60,calves:50,hamstrings:40}},
  {id:'o2', name:'Jazda na rowerze (Cycling)',                                     muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'cardio',      level:'łatwy',       muscles:{quads:70,glutes:50,calves:30}},
  {id:'o3', name:'Rower stacjonarny (Spinning)',                                  muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'cardio',      level:'łatwy',       muscles:{quads:70,glutes:50}},
  {id:'o4', name:'Wioślarz (Rowing Machine)',                                     muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Nogi','Biceps'], category:'cardio',      level:'łatwy',       muscles:{lats:70,quads:50,biceps:40}},
  {id:'o5', name:'Orbitrek (Elliptical Trainer)',                                  muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'cardio',      level:'łatwy',       muscles:{quads:60,glutes:50,calves:30}},
  {id:'o6', name:'Stepper (Stair Machine)',                                        muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'cardio',      level:'łatwy',       muscles:{quads:70,glutes:70,calves:40}},
  {id:'o7', name:'Pływanie (Swimming)',                                            muscle:'Plecy',  sub:'Najszerszy grzbiet', aux:['Barki','Klatka'], category:'cardio',    level:'łatwy',       muscles:{lats:70,frontShoulder:60,chest:50}},
  {id:'o8', name:'Marszobieg z obciążeniem (Rucking)',                            muscle:'Nogi',   sub:'Czworogłowe',     aux:['Plecy'],           category:'cardio',      level:'łatwy',       muscles:{quads:50,calves:40,traps:30}},
  {id:'o9', name:'Skakanka (Jump Rope)',                                           muscle:'Łydki',  sub:'Łydki',           aux:[],                  category:'cardio',      level:'łatwy',       muscles:{calves:80,quads:30}},
  {id:'o10',name:'Sprinty (Sprints)',                                              muscle:'Nogi',   sub:'Czworogłowe',     aux:['Pośladki'],        category:'cardio',      level:'średni',      muscles:{quads:80,glutes:70,hamstrings:60,calves:50}},

  // ── ROZSZERZONA BAZA ──
  {id:'p1',name:'Wyciskanie z pinami (Bench Pin Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:100,triceps:50}},
  {id:'p2',name:'Wiosłowanie leżąc (Bench Pull)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:80,biceps:50}},
  {id:'p3',name:'Pullover ze sztangą ugiętymi ramionami (Bent Arm Barbell Pullover)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Plecy'],category:'izolacja',level:'średni',muscles:{chest:80,lats:60}},
  {id:'p4',name:'Wyciskanie na wyciągu (Cable Chest Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:100,triceps:35}},
  {id:'p5',name:'Wyciskanie hantli wąskim chwytem (Close Grip Dumbbell Bench Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'średni',muscles:{chest:70,triceps:90}},
  {id:'p6',name:'Pompki nogi w górze (Decline Push Up)',muscle:'Klatka',sub:'Górna klatka',aux:['Triceps','Barki'],category:'wielostawowe',level:'łatwy',muscles:{chest:85,triceps:45,frontShoulder:40}},
  {id:'p7',name:'Pompki w pionie (Decline Pike Push Ups)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'średni',muscles:{frontShoulder:90,triceps:50}},
  {id:'p8',name:'Pompki z deficytu (Deficit Push Ups)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'średni',muscles:{chest:85,triceps:45}},
  {id:'p9',name:'Wyciskanie hantli na ławce (Dumbbell Bench Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps','Barki'],category:'wielostawowe',level:'łatwy',muscles:{chest:100,triceps:45,frontShoulder:30}},
  {id:'p10',name:'Rozpiętki w leżeniu przodem na skosie (Dumbbell Prone Incline Fly)',muscle:'Klatka',sub:'Górna klatka',aux:[],category:'izolacja',level:'łatwy',muscles:{chest:90}},
  {id:'p11',name:'Pompki z podwyższeniem (Incline Push Ups)',muscle:'Klatka',sub:'Dolna klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:70,triceps:40}},
  {id:'p12',name:'Wyciskanie izolateralne (Iso-Lateral Bench Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:100,triceps:40}},
  {id:'p13',name:'Maszyna klatka izolateralna (Iso-Lateral Chest Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:100,triceps:35}},
  {id:'p14',name:'Izolateralna skośna w dół (Iso-Lateral Decline Chest Press)',muscle:'Klatka',sub:'Dolna klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:95,triceps:35}},
  {id:'p15',name:'Izolateralna skośna w górę (Iso-Lateral Incline Chest Press)',muscle:'Klatka',sub:'Górna klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:90,triceps:35}},
  {id:'p16',name:'Wyciskanie z pauzą (Paused Bench Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:100,triceps:55}},
  {id:'p17',name:'Wyciskanie skośne z pauzą (Paused Incline Bench Press)',muscle:'Klatka',sub:'Górna klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:90,triceps:50}},
  {id:'p18',name:'Rozpiętki przodem na skosie (Prone Incline Fly)',muscle:'Klatka',sub:'Górna klatka',aux:[],category:'izolacja',level:'łatwy',muscles:{chest:90}},
  {id:'p19',name:'Wyciskanie szerokim chwytem na maszynie (Wide Grip Chest Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:100,triceps:30}},
  {id:'p20',name:'Wyciskanie Larsen z hantlami (Dumbbell Larsen Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:100,triceps:55}},
  {id:'p21',name:'Wyciskanie na podłodze ze sztangą (Floor Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'średni',muscles:{chest:90,triceps:60}},
  {id:'p22',name:'Wyciskanie hantli z pinami (Dumbbell Pin Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:100,triceps:50}},
  {id:'p23',name:'Rozpiętki na maszynie (Machine Chest Fly)',muscle:'Klatka',sub:'Środkowa klatka',aux:[],category:'izolacja',level:'łatwy',muscles:{chest:100}},
  {id:'p24',name:'Rozpiętki pec deck (Machine Pec Fly)',muscle:'Klatka',sub:'Środkowa klatka',aux:[],category:'izolacja',level:'łatwy',muscles:{chest:100}},
  {id:'p25',name:'Wyciskanie skośne w Smithie (Smith Machine Incline Bench Press)',muscle:'Klatka',sub:'Górna klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:90,triceps:35}},
  {id:'p26',name:'Pompki łucznicze (Archer Push Ups)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:80,triceps:80}},
  {id:'p27',name:'Pompki z klaśnięciem (Clap Push Ups)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{chest:80,triceps:50}},
  {id:'p28',name:'Pompki kobra na kolanach (Knee Cobra Push Ups)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:70,triceps:40}},
  {id:'p29',name:'Wyciskanie TRX (TRX Chest Press)',muscle:'Klatka',sub:'Środkowa klatka',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{chest:80,triceps:40}},
  {id:'p30',name:'Wiosłowanie ze sztangą w przodopochyleniu (Barbell Flexion Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:80,traps:70,biceps:50}},
  {id:'p31',name:'Martwy ciąg za plecami (Behind the Back Deadlift)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:90,traps:80,glutes:50}},
  {id:'p32',name:'Wiosłowanie w skłonie na wyciągu (Cable Bent Over Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:85,traps:55,biceps:45}},
  {id:'p33',name:'Wiosłowanie T-bar z podparciem (Chest Supported T-Bar Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:85,traps:60,biceps:45}},
  {id:'p34',name:'Podciąganie podchwytem (Chin Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:90,biceps:75}},
  {id:'p35',name:'Podciąganie wąskim chwytem (Close Grip Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:100,biceps:65}},
  {id:'p36',name:'Wiszenie na drążku (Dead Hang)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Brzuch'],category:'izolacja',level:'łatwy',muscles:{lats:40,forearms:60}},
  {id:'p37',name:'Wiosłowanie dwoma kettlebell (Double Kettlebell Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:80,traps:60,biceps:45}},
  {id:'p38',name:'Wiosłowanie z hantlami leżąc (Dumbbell Bench Pull)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:80,biceps:45}},
  {id:'p39',name:'Podciąganie wysoko (High Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,biceps:60,traps:50}},
  {id:'p40',name:'Wiosłowanie wysoko izolateralne (Iso-Lateral High Row)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:100,biceps:45}},
  {id:'p41',name:'Wiosłowanie nisko izolateralne (Iso-Lateral Low Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:80,traps:60,biceps:45}},
  {id:'p42',name:'Wiosłowanie izolateralne (Iso-Lateral Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:85,biceps:45}},
  {id:'p43',name:'Wiosłowanie na maszynie (Machine Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:80,traps:55,biceps:45}},
  {id:'p44',name:'Wiosłowanie jedną ręką na wyciągu (One Arm Seated Cable Row)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'izolacja',level:'łatwy',muscles:{lats:100,biceps:40}},
  {id:'p45',name:'Martwy ciąg semi-sumo (Semi-Sumo Deadlift)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi','Pośladki'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:90,glutes:80,hamstrings:60}},
  {id:'p46',name:'Wiosłowanie w skłonie w Smithie (Smith Machine Bent Over Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:80,traps:55,biceps:45}},
  {id:'p47',name:'Wiosłowanie odwróconym chwytem w Smithie (Smith Machine Reverse Grip Row)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:90,biceps:60}},
  {id:'p48',name:'Wiosłowanie T-bar leżąc (T Bar Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:80,traps:70,biceps:45}},
  {id:'p49',name:'Wiosłowanie w front leverze (Tuck Front Lever Row)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,abs:60,biceps:50}},
  {id:'p50',name:'Maszyna trakcja pionowa (Vertical Traction Machine)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:100,biceps:40}},
  {id:'p51',name:'Podciąganie szerokim chwytem (Wide Grip Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{lats:100,biceps:50}},
  {id:'p52',name:'Szrugi na wyciągu (Cable Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'izolacja',level:'łatwy',muscles:{traps:100}},
  {id:'p53',name:'Szrugi z hex barem (Hex Bar Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'izolacja',level:'łatwy',muscles:{traps:100}},
  {id:'p54',name:'Szrugi na maszynie (Machine Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'izolacja',level:'łatwy',muscles:{traps:100}},
  {id:'p55',name:'Szrugi dynamiczne ze sztangą (Barbell Power Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'wielostawowe',level:'zaawansowany',muscles:{traps:100,lowerBack:30}},
  {id:'p56',name:'Superman (Superman)',muscle:'Plecy',sub:'Dolne plecy',aux:['Pośladki'],category:'core',level:'łatwy',muscles:{lowerBack:90,glutes:50}},
  {id:'p57',name:'Wiosłowanie odwrócone przy stole (Table Inverted Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:75,biceps:40}},
  {id:'p58',name:'Wiosłowanie odwrócone jedną ręką (Single Arm Inverted Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:80,biceps:45}},
  {id:'p59',name:'Szrugi w Smithie (Smith Machine Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'izolacja',level:'łatwy',muscles:{traps:100}},
  {id:'p60',name:'Back lever (Back Lever)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:90,abs:70}},
  {id:'p61',name:'Front lever (Front Lever)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,abs:80}},
  {id:'p62',name:'Ściąganie drążka klęcząc jedną ręką (Half Kneeling One Arm Lat Pulldown)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'izolacja',level:'łatwy',muscles:{lats:100,biceps:40}},
  {id:'p63',name:'Ściąganie krzyżowe (Cross Body Lat Pull Around)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:[],category:'izolacja',level:'łatwy',muscles:{lats:90}},
  {id:'p64',name:'Ściąganie drążka jedną ręką górny (One Arm Lat Pulldown)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'izolacja',level:'łatwy',muscles:{lats:100,biceps:40}},
  {id:'p65',name:'Ściąganie jedną ręką (One Arm Pulldown)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'izolacja',level:'łatwy',muscles:{lats:100,biceps:40}},
  {id:'p66',name:'Wiosłowanie z hantlem (Dumbbell Row)',muscle:'Plecy',sub:'Środkowe plecy',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:85,traps:45,biceps:45}},
  {id:'p67',name:'Podciąg rwania (Snatch Pull)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,traps:70,quads:60}},
  {id:'p68',name:'Podciąganie łucznicze (Archer Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,biceps:60}},
  {id:'p69',name:'Podciąganie z asystą (Assisted Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:90,biceps:55}},
  {id:'p70',name:'Podciąganie podchwytem z asystą (Assisted Chin Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:90,biceps:70}},
  {id:'p71',name:'Podciąganie z taśmą oporową (Band Assisted Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:90,biceps:55}},
  {id:'p72',name:'Podciąganie z klaśnięciem (Clap Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,biceps:60}},
  {id:'p73',name:'Muscle up z asystą (Assisted Muscle Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Triceps','Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:90,triceps:70,biceps:60}},
  {id:'p74',name:'Podciąganie jedną ręką (One Arm Pull Ups)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,biceps:80}},
  {id:'p75',name:'Podciąganie TRX (TRX Pull Up)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{lats:85,biceps:45}},
  {id:'p76',name:'Szrugi z hantlami (Dumbbell Shrug)',muscle:'Plecy',sub:'Czworoboczny',aux:[],category:'izolacja',level:'łatwy',muscles:{traps:100}},
  {id:'p77',name:'Wznosy sztangi przodem (Barbell Front Raise)',muscle:'Barki',sub:'Przedni bark',aux:[],category:'izolacja',level:'łatwy',muscles:{frontShoulder:100}},
  {id:'p78',name:'Rotacja zewnętrzna na wyciągu (Cable External Rotation)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:70}},
  {id:'p79',name:'Rotacja wewnętrzna na wyciągu (Cable Internal Rotation)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{frontShoulder:50}},
  {id:'p80',name:'Rotacja zewnętrzna z hantlem (Dumbbell External Rotation)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:70}},
  {id:'p81',name:'Facepull z hantlem (Dumbbell Face Pull)',muscle:'Barki',sub:'Tylny bark',aux:['Plecy'],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100,traps:40}},
  {id:'p82',name:'Unoszenie hantli wysoko (Dumbbell High Pull)',muscle:'Barki',sub:'Boczny bark',aux:['Biceps'],category:'wielostawowe',level:'średni',muscles:{midShoulder:80,frontShoulder:60,biceps:40,traps:60}},
  {id:'p83',name:'Wznosy Y na skosie (Dumbbell Incline Y Raise)',muscle:'Barki',sub:'Tylny bark',aux:['Plecy'],category:'izolacja',level:'łatwy',muscles:{rearShoulder:80,traps:70}},
  {id:'p84',name:'Wznosy hantli (Dumbbell Raise)',muscle:'Barki',sub:'Boczny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{midShoulder:90}},
  {id:'p85',name:'Odwrotne rozpiętki z hantlami (Dumbbell Rear Delt Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100,traps:30}},
  {id:'p86',name:'Wiosłowanie tylny bark z hantlami (Dumbbell Rear Delt Row)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100,traps:40}},
  {id:'p87',name:'Wznosy odwrotne z hantlami (Dumbbell Reverse Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100}},
  {id:'p88',name:'Wiosłowanie do brody z hantlami (Dumbbell Upright Row)',muscle:'Barki',sub:'Boczny bark',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{midShoulder:80,frontShoulder:55,biceps:40,traps:60}},
  {id:'p89',name:'Wiosłowanie do brody EZ (EZ Bar Upright Row)',muscle:'Barki',sub:'Boczny bark',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{midShoulder:80,frontShoulder:55,biceps:40,traps:65}},
  {id:'p90',name:'Wyciskanie w staniu na rękach (Handstand Push Ups)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:70,triceps:60}},
  {id:'p91',name:'Wyciskanie izolateralne barki (Iso-Lateral Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'p92',name:'Odwrotne rozpiętki na maszynie (Machine Rear Delt Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100}},
  {id:'p93',name:'Wyciskanie militarne — sztanga (Military Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:60,triceps:50}},
  {id:'p94',name:'Wznosy przodem jedną ręką (One Arm Cable Front Raise)',muscle:'Barki',sub:'Przedni bark',aux:[],category:'izolacja',level:'łatwy',muscles:{frontShoulder:100}},
  {id:'p95',name:'Odwrotne rozpiętki jedną ręką (One Arm Cable Reverse Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100}},
  {id:'p96',name:'Boczne unoszenie jedną ręką (One Arm Dumbbell Lateral Raise)',muscle:'Barki',sub:'Boczny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{midShoulder:100}},
  {id:'p97',name:'Pompki w piramidce (Pike Push Ups)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:85,triceps:45}},
  {id:'p98',name:'Boczne unoszenie siedząc (Seated Dumbbell Lateral Raise)',muscle:'Barki',sub:'Boczny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{midShoulder:100}},
  {id:'p99',name:'Wyciskanie militarne siedząc (Seated Military Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:60,triceps:50}},
  {id:'p100',name:'Wyciskanie siedząc (Seated Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'p101',name:'Wyciskanie barki (Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'p102',name:'Wyciskanie w Smithie barki (Seated Smith Machine Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'p103',name:'Boczne unoszenie na maszynie stojąc (Standing Machine Lateral Raise)',muscle:'Barki',sub:'Boczny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{midShoulder:100}},
  {id:'p104',name:'Wznosy Y TRX (TRX Deltoid Y Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:90,traps:50}},
  {id:'p105',name:'Wyciskanie TRX (TRX Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'średni',muscles:{frontShoulder:90,triceps:45}},
  {id:'p106',name:'Rozpiętki T na TRX (TRX T Fly)',muscle:'Barki',sub:'Tylny bark',aux:[],category:'izolacja',level:'łatwy',muscles:{rearShoulder:100,traps:40}},
  {id:'p107',name:'Wyciskanie Z-press z hantlami (Dumbbell Z Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:60,triceps:40,abs:40}},
  {id:'p108',name:'Wyciskanie Z-press ze sztangą (Z Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:60,triceps:40,abs:40}},
  {id:'p109',name:'Wznosy przodem w leżeniu na skosie (Dumbbell Prone Incline Front Raise)',muscle:'Barki',sub:'Przedni bark',aux:[],category:'izolacja',level:'łatwy',muscles:{frontShoulder:100}},
  {id:'p110',name:'Wyciskanie barków z hantlami (Dumbbell Shoulder Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:100,midShoulder:60,triceps:40}},
  {id:'p111',name:'Wiosłowanie przodem kettlebell (Kettlebell Upright Front Row)',muscle:'Barki',sub:'Boczny bark',aux:['Biceps'],category:'wielostawowe',level:'łatwy',muscles:{midShoulder:80,frontShoulder:55,biceps:40}},
  {id:'p112',name:'Planche (Planche)',muscle:'Barki',sub:'Przedni bark',aux:['Brzuch','Klatka'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,abs:80,chest:60}},
  {id:'p113',name:'Pompki planche (Planche Push Ups)',muscle:'Barki',sub:'Przedni bark',aux:['Klatka','Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,chest:60,abs:70}},
  {id:'p114',name:'Szarpnięcie siłowe (Power Jerk)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,triceps:50,quads:55}},
  {id:'p115',name:'Wyciskanie z odpychiem (Push Jerk)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,triceps:50,quads:40}},
  {id:'p116',name:'Szarpnięcie nożycowe (Split Jerk)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,triceps:50,quads:60}},
  {id:'p117',name:'Pompki w piramidce na kolanach (Knee Pike Push Ups)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'łatwy',muscles:{frontShoulder:80,triceps:40}},
  {id:'p118',name:'Uginanie skupione ze sztangą (Barbell Concentration Curl)',muscle:'Biceps',sub:'Biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p119',name:'Uginanie młotkowe na wyciągu (Cable Hammer Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:80,forearms:60}},
  {id:'p120',name:'Uginanie z zamachem (Cheat Curl)',muscle:'Biceps',sub:'Biceps',aux:[],category:'izolacja',level:'zaawansowany',muscles:{biceps:100}},
  {id:'p121',name:'Uginanie skupione z hantlem (Dumbbell Concentration Curl)',muscle:'Biceps',sub:'Biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p122',name:'Uginanie odwrócone z hantlami (Dumbbell Reverse Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:60,forearms:90}},
  {id:'p123',name:'Uginanie pająk z hantlami (Dumbbell Spider Curl)',muscle:'Biceps',sub:'Głowa długa biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p124',name:'Uginanie na wyciągu leżąc (Lying Cable Curl)',muscle:'Biceps',sub:'Głowa długa biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p125',name:'Uginanie na modlitewniku jedną ręką (One Arm Dumbbell Preacher Curl)',muscle:'Biceps',sub:'Głowa krótka biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p126',name:'Uginanie kettlebell jedną ręką (One Arm Kettlebell Bicep Curl)',muscle:'Biceps',sub:'Biceps',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:100}},
  {id:'p127',name:'Uginanie odwrócone ze sztangą (Reverse Barbell Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:90,biceps:50}},
  {id:'p128',name:'Uginanie nadgarstka odwrócone (Reverse Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p129',name:'Uginanie nadgarstka odwrócone na wyciągu (Cable Reverse Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p130',name:'Uginanie nadgarstka na wyciągu (Cable Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p131',name:'Uginanie nadgarstka z hantlem (Dumbbell Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p132',name:'Uginanie nadgarstka odwrócone z hantlem (Dumbbell Reverse Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p133',name:'Uginanie młotkowe na ręczniku (Towel Hammer Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{biceps:80,forearms:70}},
  {id:'p134',name:'Ściskacz do dłoni (Hand Grippers)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p135',name:'Uginanie nadgarstka jedną ręką na wyciągu (One Arm Cable Wrist Curl)',muscle:'Biceps',sub:'Brachialis',aux:[],category:'izolacja',level:'łatwy',muscles:{forearms:100}},
  {id:'p136',name:'Dipsy z asystą (Assisted Dips)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'łatwy',muscles:{triceps:90,chest:40}},
  {id:'p137',name:'Prostowanie triceps klęcząc (Bodyweight Kneeling Tricep Extension)',muscle:'Triceps',sub:'Głowa długa triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p138',name:'Prostowanie nad głową z masą ciała (Bodyweight Overhead Tricep Extension)',muscle:'Triceps',sub:'Głowa długa triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p139',name:'Prostowanie triceps z masą ciała (Bodyweight Tricep Extension)',muscle:'Triceps',sub:'Triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p140',name:'Odrzut na wyciągu (Cable Kickback)',muscle:'Triceps',sub:'Głowa boczna',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p141',name:'Odrzut triceps na wyciągu (Cable Tricep Kickback)',muscle:'Triceps',sub:'Głowa boczna',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p142',name:'Dipsy (Dips)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'średni',muscles:{triceps:100,chest:50}},
  {id:'p143',name:'Prostowanie nad głową z hantlem (Dumbbell Overhead Tricep Extension)',muscle:'Triceps',sub:'Głowa długa triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p144',name:'Odrzut z hantlem (Dumbbell Tricep Kickback)',muscle:'Triceps',sub:'Głowa boczna',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p145',name:'Prostowanie leżąc z hantlem (Lying Dumbbell Tricep Extension)',muscle:'Triceps',sub:'Głowa długa triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p146',name:'Prostowanie triceps na maszynie (Machine Tricep Extension)',muscle:'Triceps',sub:'Triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p147',name:'Pompki jedną ręką (One Arm Push Ups)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'zaawansowany',muscles:{triceps:80,chest:70}},
  {id:'p148',name:'Pompki odwróconym chwytem (Reverse Grip Push Ups)',muscle:'Triceps',sub:'Głowa długa triceps',aux:['Klatka'],category:'wielostawowe',level:'średni',muscles:{triceps:90,chest:50}},
  {id:'p149',name:'Dipsy rosyjskie (Russian Dips)',muscle:'Triceps',sub:'Triceps',aux:[],category:'wielostawowe',level:'zaawansowany',muscles:{triceps:100}},
  {id:'p150',name:'Dipsy na maszynie siedząc (Seated Dip Machine)',muscle:'Triceps',sub:'Triceps',aux:[],category:'wielostawowe',level:'łatwy',muscles:{triceps:100}},
  {id:'p151',name:'Pompki tiger bend (Tiger Bend Push Ups)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'zaawansowany',muscles:{triceps:100,chest:50}},
  {id:'p152',name:'Prostowanie triceps (Tricep Extension)',muscle:'Triceps',sub:'Triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p153',name:'Popychanie triceps (Tricep Pushdown)',muscle:'Triceps',sub:'Triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p154',name:'Prostowanie leżąc EZ (EZ Bar Lying Tricep Extension)',muscle:'Triceps',sub:'Głowa długa triceps',aux:[],category:'izolacja',level:'łatwy',muscles:{triceps:100}},
  {id:'p155',name:'Pompki na pięściach (Knuckle Push Ups)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'łatwy',muscles:{triceps:60,chest:80}},
  {id:'p156',name:'Pompki wąskim chwytem (Close Grip Push Up)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'łatwy',muscles:{triceps:90,chest:60}},
  {id:'p157',name:'Pompki rosyjskie (Russian Push Ups)',muscle:'Triceps',sub:'Triceps',aux:['Klatka'],category:'wielostawowe',level:'zaawansowany',muscles:{triceps:90,chest:60}},
  {id:'p158',name:'Rowerek leżąc (Air Bike)',muscle:'Brzuch',sub:'Dolny brzuch',aux:[],category:'core',level:'łatwy',muscles:{abs:85}},
  {id:'p159',name:'Przysiad hack ze sztangą (Barbell Hack Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:100,glutes:50}},
  {id:'p160',name:'Wykroki w tył ze sztangą (Barbell Reverse Lunge)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:85,glutes:75}},
  {id:'p161',name:'Przysiad na skrzyni z masą ciała (Bodyweight Box Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:90,glutes:60}},
  {id:'p162',name:'Good morning z masą ciała (Bodyweight Good Morning)',muscle:'Plecy',sub:'Dolne plecy',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{lowerBack:70,hamstrings:80,glutes:50}},
  {id:'p163',name:'Przysiad z masą ciała (Bodyweight Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:90,glutes:55}},
  {id:'p164',name:'Prostowanie nóg na wyciągu (Cable Leg Extension)',muscle:'Nogi',sub:'Czworogłowe',aux:[],category:'izolacja',level:'łatwy',muscles:{quads:100}},
  {id:'p165',name:'Wznosy łydek w opadzie (Donkey Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p166',name:'Przysiad bułgarski z hantlami (Dumbbell Bulgarian Split Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:75}},
  {id:'p167',name:'Martwy ciąg rumuński z hantlami (Dumbbell Romanian Deadlift)',muscle:'Nogi',sub:'Dwugłowe ud',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{hamstrings:90,glutes:70,lowerBack:50}},
  {id:'p168',name:'Przysiad nożycowy z hantlami (Dumbbell Split Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:85,glutes:65}},
  {id:'p169',name:'Wznosy łydek na hex barze (Elevated Hex Bar Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p170',name:'Przysiad ze skokiem wybuchowym (Explosive Squat Jump)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:70,calves:40}},
  {id:'p171',name:'Odwodzenie bioder w leżeniu (Floor Hip Abduction)',muscle:'Pośladki',sub:'Pośladki małe',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:80}},
  {id:'p172',name:'Wyprost biodra w leżeniu (Floor Hip Extension)',muscle:'Pośladki',sub:'Pośladki',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:100,hamstrings:40}},
  {id:'p173',name:'Marsz na pośladkach (Glute March)',muscle:'Pośladki',sub:'Pośladki',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:90,abs:40}},
  {id:'p174',name:'Przysiad goblet (Goblet Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:90,glutes:60}},
  {id:'p175',name:'Półprzysiad (Half Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:80,glutes:50}},
  {id:'p176',name:'Dociskanie piętą (Heel Press)',muscle:'Pośladki',sub:'Pośladki',aux:['Nogi'],category:'izolacja',level:'łatwy',muscles:{glutes:90,hamstrings:50}},
  {id:'p177',name:'Dotykanie pięty (Heel Touch)',muscle:'Brzuch',sub:'Skośne brzucha',aux:[],category:'core',level:'łatwy',muscles:{abs:75}},
  {id:'p178',name:'Przysiad z podwyższonymi piętami (Heel-Elevated Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:50}},
  {id:'p179',name:'Odwodzenie bioder (Hip Abduction)',muscle:'Pośladki',sub:'Pośladki małe',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:80}},
  {id:'p180',name:'Wyprost biodra (Hip Extension)',muscle:'Pośladki',sub:'Pośladki',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:100,hamstrings:50}},
  {id:'p181',name:'Hip thrust (Hip Thrust)',muscle:'Pośladki',sub:'Pośladki',aux:['Nogi'],category:'wielostawowe',level:'średni',muscles:{glutes:100,hamstrings:50}},
  {id:'p182',name:'Pozioma prasa nóg (Horizontal Leg Press)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:55}},
  {id:'p183',name:'Martwy ciąg jednonóż kettlebell (Kettlebell Single Leg Deadlift)',muscle:'Nogi',sub:'Dwugłowe ud',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{hamstrings:90,glutes:80,lowerBack:50}},
  {id:'p184',name:'Przysiad z landmine (Landmine Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:90,glutes:60}},
  {id:'p185',name:'Uginanie nóg na maszynie (Machine Leg Curl)',muscle:'Nogi',sub:'Dwugłowe ud',aux:[],category:'izolacja',level:'łatwy',muscles:{hamstrings:100}},
  {id:'p186',name:'Prostowanie nóg na maszynie (Machine Leg Extension)',muscle:'Nogi',sub:'Czworogłowe',aux:[],category:'izolacja',level:'łatwy',muscles:{quads:100}},
  {id:'p187',name:'Prasa nóg na maszynie (Machine Leg Press)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:55}},
  {id:'p188',name:'Przysiad wahadłowy (Pendulum Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:60}},
  {id:'p189',name:'Przysiad z pinami (Pin Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:100,glutes:60}},
  {id:'p190',name:'Wykroki w tył (Reverse Lunge)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:85,glutes:70}},
  {id:'p191',name:'Prostowanie nóg siedząc (Seated Leg Extension)',muscle:'Nogi',sub:'Czworogłowe',aux:[],category:'izolacja',level:'łatwy',muscles:{quads:100}},
  {id:'p192',name:'Prasa nóg siedząc (Seated Leg Press)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:55}},
  {id:'p193',name:'Unoszenie nogi w bok (Side Leg Raise)',muscle:'Pośladki',sub:'Pośladki małe',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:80}},
  {id:'p194',name:'Wykroki w bok (Side Lunge)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:80,glutes:70}},
  {id:'p195',name:'Odwodzenie biodra w leżeniu bokiem (Side Lying Hip Abduction)',muscle:'Pośladki',sub:'Pośladki małe',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:80}},
  {id:'p196',name:'Wyskok na skrzynię jednonóż (Single Leg Box Jump)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:90,glutes:70,calves:40}},
  {id:'p197',name:'Martwy ciąg rumuński jednonóż (Single Leg Romanian Deadlift)',muscle:'Nogi',sub:'Dwugłowe ud',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{hamstrings:90,glutes:80}},
  {id:'p198',name:'Uginanie nóg jednonóż siedząc (Single Leg Seated Leg Curl)',muscle:'Nogi',sub:'Dwugłowe ud',aux:[],category:'izolacja',level:'łatwy',muscles:{hamstrings:100}},
  {id:'p199',name:'Przysiad na jednej nodze (Single Leg Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:100,glutes:60}},
  {id:'p200',name:'Wznosy łydek na saniach (Sled Press Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p201',name:'Pchanie sań (Sled Push)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:80,calves:40}},
  {id:'p202',name:'Wznosy łydek w Smithie (Smith Machine Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p203',name:'Przysiad w Smithie (Smith Machine Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:60}},
  {id:'p204',name:'Balans rwania (Snatch Balance)',muscle:'Nogi',sub:'Czworogłowe',aux:['Barki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:70,frontShoulder:60,lowerBack:50}},
  {id:'p205',name:'Przysiad (Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:100,glutes:60}},
  {id:'p206',name:'Przysiad ze skokiem (Squat Jump)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:65,calves:35}},
  {id:'p207',name:'Unoszenie palców stopy (Tibialis Raise)',muscle:'Łydki',sub:'Piszczel',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:60}},
  {id:'p208',name:'Wchodzenie na skrzynię Poliquin (Dumbbell Poliquin Step Up)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:65}},
  {id:'p209',name:'Wznosy łydek w marszu (Dumbbell Walking Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p210',name:'Wznosy łydek na maszynie (Machine Calf Raise)',muscle:'Łydki',sub:'Łydki',aux:[],category:'izolacja',level:'łatwy',muscles:{calves:100}},
  {id:'p211',name:'Skłon boczny z hantlem (Dumbbell Side Bend)',muscle:'Brzuch',sub:'Skośne brzucha',aux:[],category:'core',level:'łatwy',muscles:{abs:80}},
  {id:'p212',name:'Wykroki wsteczne TRX (TRX Reverse Lunge)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:85,glutes:70}},
  {id:'p213',name:'Przysiad TRX (TRX Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{quads:90,glutes:60}},
  {id:'p214',name:'Wykrok zawieszony TRX (TRX Suspended Lunge)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'średni',muscles:{quads:90,glutes:70}},
  {id:'p215',name:'Przysiad Zercher (Zercher Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki','Brzuch'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:100,glutes:60,abs:50}},
  {id:'p216',name:'Martwy ciąg Zercher (Zercher Deadlift)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:90,quads:70,glutes:60}},
  {id:'p217',name:'Przysiad bułgarski Zercher (Zercher Bulgarian Split Squat)',muscle:'Nogi',sub:'Czworogłowe',aux:['Pośladki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:90,glutes:75}},
  {id:'p218',name:'Maszyna abcoaster (Abcoaster)',muscle:'Brzuch',sub:'Dolny brzuch',aux:[],category:'core',level:'łatwy',muscles:{abs:90}},
  {id:'p219',name:'Wiosłujący piesek (Bird Dog)',muscle:'Brzuch',sub:'Mięśnie proste',aux:['Plecy'],category:'core',level:'łatwy',muscles:{abs:70,lowerBack:60}},
  {id:'p220',name:'Rąbanie drewna na wyciągu (Cable Woodchopper)',muscle:'Brzuch',sub:'Skośne brzucha',aux:['Barki'],category:'core',level:'łatwy',muscles:{abs:80,frontShoulder:40}},
  {id:'p221',name:'Unoszenie kolan na fotelu kapitańskim (Captains Chair Knee Raise)',muscle:'Brzuch',sub:'Dolny brzuch',aux:[],category:'core',level:'łatwy',muscles:{abs:85}},
  {id:'p222',name:'Unoszenie nóg na fotelu kapitańskim (Captains Chair Leg Raise)',muscle:'Brzuch',sub:'Dolny brzuch',aux:[],category:'core',level:'średni',muscles:{abs:90}},
  {id:'p223',name:'Spięcia brzucha (Crunches)',muscle:'Brzuch',sub:'Mięśnie proste',aux:[],category:'core',level:'łatwy',muscles:{abs:100}},
  {id:'p224',name:'Sit-upy żabie (Frog Sit-Ups)',muscle:'Brzuch',sub:'Mięśnie proste',aux:[],category:'core',level:'łatwy',muscles:{abs:100}},
  {id:'p225',name:'Spięcia na wyciągu górnym (High Pulley Crunch)',muscle:'Brzuch',sub:'Mięśnie proste',aux:[],category:'core',level:'łatwy',muscles:{abs:100}},
  {id:'p226',name:'Sit-up odwrócony na ławce skośnej (Inverted Decline Sit-up)',muscle:'Brzuch',sub:'Mięśnie proste',aux:[],category:'core',level:'zaawansowany',muscles:{abs:100}},
  {id:'p227',name:'Plank z przechyłem (Plank Lean)',muscle:'Brzuch',sub:'Mięśnie proste',aux:['Barki'],category:'core',level:'łatwy',muscles:{abs:90,frontShoulder:40}},
  {id:'p228',name:'Plank boczny z odwodzeniem (Side Plank Hip Abduction)',muscle:'Brzuch',sub:'Skośne brzucha',aux:['Pośladki'],category:'core',level:'średni',muscles:{abs:80,glutes:60}},
  {id:'p230',name:'Wspinaczka górska TRX (TRX Mountain Climbers)',muscle:'Brzuch',sub:'Mięśnie proste',aux:['Barki'],category:'core',level:'łatwy',muscles:{abs:80,frontShoulder:30}},
  {id:'p231',name:'Plank TRX (TRX Plank)',muscle:'Brzuch',sub:'Mięśnie proste',aux:['Barki'],category:'core',level:'łatwy',muscles:{abs:90,frontShoulder:30}},
  {id:'p232',name:'Mostek biodrowy TRX (TRX Glute Bridge)',muscle:'Pośladki',sub:'Pośladki',aux:[],category:'izolacja',level:'łatwy',muscles:{glutes:100,hamstrings:40}},
  {id:'p233',name:'Liny bojowe (Battle Ropes)',muscle:'Barki',sub:'Boczny bark',aux:['Brzuch'],category:'wielostawowe',level:'średni',muscles:{midShoulder:70,frontShoulder:60,abs:60}},
  {id:'p234',name:'Pajacyki (Jumping Jacks)',muscle:'Nogi',sub:'Czworogłowe',aux:['Barki'],category:'cardio',level:'łatwy',muscles:{quads:40,calves:40,midShoulder:30}},
  {id:'p235',name:'Bieżnia (Treadmill)',muscle:'Nogi',sub:'Czworogłowe',aux:[],category:'cardio',level:'łatwy',muscles:{quads:55,calves:45}},
  {id:'p236',name:'Rzut piłką lekarską (Wall Ball)',muscle:'Nogi',sub:'Czworogłowe',aux:['Barki','Brzuch'],category:'wielostawowe',level:'średni',muscles:{quads:80,glutes:60,frontShoulder:50,abs:40}},
  {id:'p237',name:'Przysiad przy ścianie (Wall Sit)',muscle:'Nogi',sub:'Czworogłowe',aux:[],category:'izolacja',level:'łatwy',muscles:{quads:100}},
  {id:'p238',name:'Swing kettlebell naprzemianstronny (Alternating Arm Kettlebell Swing)',muscle:'Pośladki',sub:'Pośladki',aux:['Plecy','Nogi'],category:'wielostawowe',level:'średni',muscles:{glutes:100,hamstrings:70,lowerBack:60}},
  {id:'p240',name:'Zarzut (Clean)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi','Barki'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,quads:60,traps:60}},
  {id:'p241',name:'Zarzut i wyciskanie (Clean and Press)',muscle:'Plecy',sub:'Dolne plecy',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,quads:60,frontShoulder:80,triceps:40}},
  {id:'p242',name:'Podciąg do zarzutu (Clean High Pull)',muscle:'Plecy',sub:'Czworoboczny',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{traps:80,frontShoulder:60,quads:55,lowerBack:70}},
  {id:'p243',name:'Podciąg zarzutu (Clean Pull)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,traps:65,quads:55}},
  {id:'p244',name:'Martwy zarzut dwóch kettlebell (Double Kettlebell Dead Clean)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:75,glutes:65,quads:55}},
  {id:'p245',name:'Martwe rwanie nożycowe kettlebell (Double Kettlebell Dead Split Snatch)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi','Barki'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,quads:65,frontShoulder:70}},
  {id:'p246',name:'Wyciskanie dwóch kettlebell (Double Kettlebell Military Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:100,midShoulder:65,triceps:50}},
  {id:'p247',name:'Szarpnięcie nożycowe kettlebell (Double Kettlebell Split Jerk)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,triceps:50,quads:60}},
  {id:'p248',name:'Rwanie huśtawkowe kettlebell (Double Kettlebell Swing Snatch)',muscle:'Pośladki',sub:'Pośladki',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{glutes:90,hamstrings:70,frontShoulder:70}},
  {id:'p249',name:'Zarzut z podwieszenia z hantlami (Dumbbell Hang Clean)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:70,glutes:60,quads:55}},
  {id:'p250',name:'Rwanie mięśniowe z hantlami (Dumbbell Muscle Snatch)',muscle:'Barki',sub:'Przedni bark',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,quads:50,traps:60}},
  {id:'p251',name:'Zarzut siłowy z hantlami (Dumbbell Power Clean)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:70,glutes:60,quads:55}},
  {id:'p252',name:'Wyciskanie z odpychiem z hantlami (Dumbbell Push Press)',muscle:'Barki',sub:'Przedni bark',aux:['Triceps','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,triceps:45,quads:35}},
  {id:'p253',name:'Rwanie z hantlem (Dumbbell Snatch)',muscle:'Plecy',sub:'Dolne plecy',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,frontShoulder:80}},
  {id:'p254',name:'Zarzut z podwieszenia (Hang Clean)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:75,glutes:65,quads:55,traps:55}},
  {id:'p255',name:'Rwanie z podwieszenia (Hang Snatch)',muscle:'Plecy',sub:'Dolne plecy',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,frontShoulder:75}},
  {id:'p256',name:'Zarzut i wyciskanie kettlebell (Kettlebell Clean and Jerk)',muscle:'Plecy',sub:'Dolne plecy',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,frontShoulder:80,triceps:40}},
  {id:'p257',name:'Martwy ciąg z kettlebell (Kettlebell Deadlift)',muscle:'Plecy',sub:'Dolne plecy',aux:['Nogi','Pośladki'],category:'wielostawowe',level:'łatwy',muscles:{lowerBack:85,glutes:65,hamstrings:55}},
  {id:'p258',name:'Wykrok z wyciskaniem kettlebell (Kettlebell Lunge Press)',muscle:'Nogi',sub:'Czworogłowe',aux:['Barki'],category:'wielostawowe',level:'średni',muscles:{quads:80,glutes:65,frontShoulder:70}},
  {id:'p259',name:'Wykrok wsteczny z wyciskaniem kettlebell (Kettlebell Offset Reverse Lunge and Press)',muscle:'Nogi',sub:'Czworogłowe',aux:['Barki'],category:'wielostawowe',level:'zaawansowany',muscles:{quads:80,glutes:65,frontShoulder:70}},
  {id:'p260',name:'Russian twist z kettlebell (Kettlebell Russian Twist)',muscle:'Brzuch',sub:'Skośne brzucha',aux:[],category:'core',level:'łatwy',muscles:{abs:80}},
  {id:'p261',name:'Swing clean kettlebell (Kettlebell Swing Clean)',muscle:'Pośladki',sub:'Pośladki',aux:['Plecy','Nogi'],category:'wielostawowe',level:'średni',muscles:{glutes:90,hamstrings:65,lowerBack:55}},
  {id:'p262',name:'Wiatraki z kettlebell (Kettlebell Windmills)',muscle:'Brzuch',sub:'Skośne brzucha',aux:['Barki','Plecy'],category:'wielostawowe',level:'zaawansowany',muscles:{abs:80,frontShoulder:60,lowerBack:50}},
  {id:'p263',name:'Rwanie mięśniowe (Muscle Snatch)',muscle:'Barki',sub:'Przedni bark',aux:['Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{frontShoulder:90,quads:50,traps:60}},
  {id:'p264',name:'Swing kettlebell jedną ręką (One Arm Kettlebell Swing)',muscle:'Pośladki',sub:'Pośladki',aux:['Plecy','Nogi'],category:'wielostawowe',level:'średni',muscles:{glutes:100,hamstrings:70,lowerBack:60}},
  {id:'p265',name:'Rwanie siłowe (Power Snatch)',muscle:'Plecy',sub:'Dolne plecy',aux:['Barki','Nogi'],category:'wielostawowe',level:'zaawansowany',muscles:{lowerBack:80,glutes:70,frontShoulder:75}},
  {id:'p266',name:'Podciąganie kombinowane z hantlami (Dumbbell Pull Pull)',muscle:'Plecy',sub:'Najszerszy grzbiet',aux:['Biceps'],category:'wielostawowe',level:'zaawansowany',muscles:{lats:100,biceps:55}},
];

function getAllExercises(){return[...EXERCISES,...state.customExercises]}
